const palette = ['#1769e0','#8c56d9','#f06b55','#00a895','#e09b19','#527286','#da4c91'];
const defaultProcesses = [{id:'P1',arrival:0,burst:8},{id:'P2',arrival:1,burst:4},{id:'P3',arrival:2,burst:12},{id:'P4',arrival:3,burst:6}];
const samples = { mixed:defaultProcesses, short:[{id:'P1',arrival:0,burst:2},{id:'P2',arrival:0,burst:3},{id:'P3',arrival:1,burst:2},{id:'P4',arrival:2,burst:4},{id:'P5',arrival:3,burst:1}], staggered:[{id:'P1',arrival:0,burst:10},{id:'P2',arrival:3,burst:3},{id:'P3',arrival:6,burst:8},{id:'P4',arrival:10,burst:2}] };
let processes=structuredClone(defaultProcesses), latestResults, playback={mode:'arr',step:0,timer:null};
const rows=document.querySelector('#processRows');
function renderRows(){rows.innerHTML=processes.map((process,index)=>`<tr><td><input data-field="id" data-index="${index}" value="${process.id}" aria-label="Process ID"></td><td><input data-field="arrival" data-index="${index}" type="number" min="0" value="${process.arrival}" aria-label="Arrival time"></td><td><input data-field="burst" data-index="${index}" type="number" min="1" value="${process.burst}" aria-label="Burst time"></td><td><button class="delete" data-remove="${index}" title="Remove ${process.id}">×</button></td></tr>`).join('');}
rows.addEventListener('input',event=>{const input=event.target;if(!input.dataset.field)return;const process=processes[Number(input.dataset.index)];process[input.dataset.field]=input.dataset.field==='id'?input.value:Number(input.value);});
rows.addEventListener('click',event=>{const button=event.target.closest('[data-remove]');if(!button||processes.length===1)return;processes.splice(Number(button.dataset.remove),1);renderRows();});
document.querySelector('#addProcess').addEventListener('click',()=>{processes.push({id:`P${processes.length+1}`,arrival:0,burst:1});renderRows();});
document.querySelectorAll('[data-sample]').forEach(button=>button.addEventListener('click',()=>{processes=structuredClone(samples[button.dataset.sample]);renderRows();}));
document.querySelector('#randomWorkload').addEventListener('click',()=>{const count=5+Math.floor(Math.random()*3);processes=Array.from({length:count},(_,index)=>({id:`P${index+1}`,arrival:Math.floor(Math.random()*9),burst:1+Math.floor(Math.random()*14)})).sort((a,b)=>a.arrival-b.arrival||a.id.localeCompare(b.id));renderRows();});
function median(values){const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:Math.ceil((sorted[middle-1]+sorted[middle])/2);}
function validate(){const fixed=Number(document.querySelector('#fixedQuantum').value),min=Number(document.querySelector('#minQuantum').value),max=Number(document.querySelector('#maxQuantum').value),switchCost=Number(document.querySelector('#switchCost').value);const valid=processes.length&&processes.every(p=>p.id.trim()&&Number.isInteger(p.arrival)&&p.arrival>=0&&Number.isInteger(p.burst)&&p.burst>0);const unique=new Set(processes.map(p=>p.id.trim())).size===processes.length;if(!valid)return 'Use non-empty process IDs, whole-number arrivals (0+) and bursts (1+).';if(!unique)return 'Each process ID must be unique.';if(!Number.isInteger(fixed)||fixed<1||!Number.isInteger(min)||min<1||!Number.isInteger(max)||max<min||!Number.isInteger(switchCost)||switchCost<0)return 'Quantums and switch cost must be whole numbers; maximum must be at least minimum.';return null;}
function simulate(source,policy,config){const all=source.map((item,index)=>({...item,index,remaining:item.burst,start:null,completion:null}));const pending=[...all].sort((a,b)=>a.arrival-b.arrival||a.index-b.index),ready=[],slices=[],trace=[];let time=0,previous=null,contextSwitches=0,overheadTime=0;const enqueue=()=>{while(pending.length&&pending[0].arrival<=time)ready.push(pending.shift());};while(pending.length||ready.length){enqueue();if(!ready.length){const next=pending[0].arrival;if(next>time)slices.push({id:'IDLE',start:time,end:next});time=next;previous=null;enqueue();}const queue=ready.map(p=>`${p.id}(${p.remaining})`);const quantum=policy==='adaptive'?Math.min(config.max,Math.max(config.min,median(ready.map(p=>p.remaining)))):config.fixed;const process=ready.shift();if(previous&&previous!==process.id){contextSwitches++;if(config.switchCost){slices.push({id:'CS',start:time,end:time+config.switchCost});time+=config.switchCost;overheadTime+=config.switchCost;enqueue();}}if(process.start===null)process.start=time;const duration=Math.min(quantum,process.remaining),start=time;time+=duration;process.remaining-=duration;slices.push({id:process.id,start,end:time,quantum});trace.push({time:start,process:process.id,quantum,queue,duration,remaining:process.remaining});enqueue();if(process.remaining>0)ready.push(process);else process.completion=time;previous=process.id;}const metrics=all.map(p=>({id:p.id,completion:p.completion,turnaround:p.completion-p.arrival,waiting:p.completion-p.arrival-p.burst,response:p.start-p.arrival}));const average=field=>metrics.reduce((total,item)=>total+item[field],0)/metrics.length,busy=all.reduce((total,p)=>total+p.burst,0);return {policy,slices,trace,metrics,contextSwitches,totalTime:time,overheadTime,utilization:busy/time*100,throughput:all.length/time,averages:{waiting:average('waiting'),turnaround:average('turnaround'),response:average('response')}};}
function colorFor(id){if(id==='IDLE')return '#aebbc5';if(id==='CS')return '#334e68';return palette[Number((id.match(/\d+/)||['0'])[0])%palette.length];}
function gantt(slices,total){return `<div class="gantt">${slices.map(slice=>`<div class="slice" title="${slice.id}: ${slice.start}–${slice.end}${slice.quantum?` (Q=${slice.quantum})`:''}" style="width:${Math.max(4,(slice.end-slice.start)/total*100)}%;background:${colorFor(slice.id)}">${slice.id}<small>${slice.start}–${slice.end}</small></div>`).join('')}</div><p class="gantt-caption">Hover a segment for its interval. <b>CS</b> shows configured context-switch overhead. Timeline ends at <b>${total}</b>.</p>`;}
function algorithmView(result,title,subtitle){return `<header><div class="algo-title"><div><h3>${title}</h3><p class="eyebrow">${subtitle}</p></div><span class="pill">${result.contextSwitches} switches</span></div></header><div class="gantt-wrap">${gantt(result.slices,result.totalTime)}</div><div class="averages"><div class="average"><b>AVG WAIT</b><span>${result.averages.waiting.toFixed(2)}</span></div><div class="average"><b>AVG TURN</b><span>${result.averages.turnaround.toFixed(2)}</span></div><div class="average"><b>CPU UTIL.</b><span>${result.utilization.toFixed(1)}%</span></div><div class="average"><b>THROUGHPUT</b><span>${result.throughput.toFixed(2)}</span></div></div><div class="metric-table"><table><thead><tr><th>PID</th><th>CT</th><th>TAT</th><th>WT</th><th>RT</th></tr></thead><tbody>${result.metrics.map(m=>`<tr><td><b>${m.id}</b></td><td>${m.completion}</td><td>${m.turnaround}</td><td>${m.waiting}</td><td>${m.response}</td></tr>`).join('')}</tbody></table></div>`;}
function comparisonChart(rr,arr){const data=[['Avg waiting',rr.averages.waiting,arr.averages.waiting],['Avg turnaround',rr.averages.turnaround,arr.averages.turnaround],['Avg response',rr.averages.response,arr.averages.response],['Switches',rr.contextSwitches,arr.contextSwitches]],maximum=Math.max(...data.flatMap(item=>item.slice(1)),1);return data.map(([label,rrValue,arrValue])=>`<div class="bar-row"><span>${label}</span><div class="bar-pair"><div class="bar" style="width:${rrValue/maximum*100}%"></div><div class="bar arr" style="width:${arrValue/maximum*100}%"></div></div><span class="bar-value">${rrValue.toFixed(1)} / ${arrValue.toFixed(1)}</span></div>`).join('');}
function renderResults(rr,arr,config){const switchDifference=rr.contextSwitches-arr.contextSwitches,waitDifference=rr.averages.waiting-arr.averages.waiting;document.querySelector('#summaryCards').innerHTML=`<div class="summary teal"><p class="summary-label">ADAPTIVE QUANTUM RULE</p><p class="summary-value">Median</p><p class="summary-note">Remaining bursts, bounded by your limits</p></div><div class="summary"><p class="summary-label">CONTEXT SWITCH DIFFERENCE</p><p class="summary-value">${Math.abs(switchDifference)}</p><p class="summary-note">ARR has ${switchDifference===0?'the same number of':switchDifference>0?'fewer':'more'} switches than RR</p></div><div class="summary amber"><p class="summary-label">TOTAL OVERHEAD TIME</p><p class="summary-value">${arr.overheadTime}</p><p class="summary-note">ARR overhead at the selected switch cost</p></div>`;document.querySelector('#comparisonChart').innerHTML=comparisonChart(rr,arr);document.querySelector('#findingTitle').textContent=switchDifference>0?'Adaptive RR reduces switching here.':switchDifference<0?'Fixed RR switches less here.':'Both policies switch equally here.';document.querySelector('#findingText').textContent=`${waitDifference>0?`ARR reduces average waiting by ${waitDifference.toFixed(2)} time units.`:waitDifference<0?`ARR increases average waiting by ${Math.abs(waitDifference).toFixed(2)} time units.`:'Both policies have identical average waiting.'} This result is specific to the selected workload and settings.`;document.querySelector('#configSummary').innerHTML=`<span>RR Q=${config.fixed}</span><span>ARR bounds ${config.min}–${config.max}</span><span>Switch cost ${config.switchCost}</span><span>${processes.length} processes</span>`;document.querySelector('#rrResults').innerHTML=algorithmView(rr,'Traditional Round Robin',`Fixed quantum: ${config.fixed}`);document.querySelector('#arrResults').innerHTML=algorithmView(arr,'Adaptive Round Robin',`Bounded median: ${config.min}–${config.max}`);document.querySelector('#emptyState').classList.add('hidden');document.querySelector('#results').classList.remove('hidden');resetPlayback();}
function currentPlayback(){return playback.mode==='arr'?latestResults.arr:latestResults.rr;}
function renderPlayback(){if(!latestResults)return;const result=currentPlayback(),trace=result.trace,item=trace[playback.step],label=playback.mode==='arr'?'Adaptive RR':'Traditional RR';document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.playback===playback.mode));document.querySelector('#liveState').innerHTML=item?`<div class="live-item"><b>SIMULATION TIME</b><span>t = ${item.time}</span></div><div class="live-item"><b>RUNNING PROCESS</b><span>${item.process}</span></div><div class="live-item"><b>TIME QUANTUM</b><span>${item.quantum}</span></div><div class="live-item"><b>CPU BURST</b><span>${item.duration} unit${item.duration===1?'':'s'}</span></div>`:`<div class="live-item"><b>STATUS</b><span>Complete</span></div><div class="live-item"><b>ALGORITHM</b><span>${label}</span></div><div class="live-item"><b>FINISH TIME</b><span>${result.totalTime}</span></div><div class="live-item"><b>SWITCHES</b><span>${result.contextSwitches}</span></div>`;document.querySelector('#progressFill').style.width=`${trace.length?((playback.step+(item?1:0))/trace.length)*100:0}%`;document.querySelector('#trace').innerHTML=trace.map((entry,index)=>`<div class="trace-item ${index===playback.step?'active':''}"><b>Step ${index+1} · t=${entry.time}</b> · ${entry.process} runs with Q=${entry.quantum}<div class="trace-queue">Ready queue: ${entry.queue.join(' → ')}</div><div class="trace-queue">After run: ${entry.remaining?`${entry.process} has ${entry.remaining} left`:`${entry.process} completes`}</div></div>`).join('');document.querySelector('#previousStep').disabled=playback.step===0;document.querySelector('#nextStep').textContent=playback.step>=trace.length?'Completed ✓':'Next step →';}
function stopAutoPlay(){if(playback.timer){clearInterval(playback.timer);playback.timer=null;document.querySelector('#autoPlay').textContent='▶ Auto play';}}
function resetPlayback(){stopAutoPlay();playback.step=0;renderPlayback();}
function movePlayback(delta){const trace=currentPlayback().trace;playback.step=Math.max(0,Math.min(trace.length,playback.step+delta));renderPlayback();if(playback.step>=trace.length)stopAutoPlay();}
document.querySelector('#nextStep').addEventListener('click',()=>{if(latestResults)movePlayback(1);});document.querySelector('#previousStep').addEventListener('click',()=>{if(latestResults)movePlayback(-1);});document.querySelector('#resetPlayback').addEventListener('click',()=>{if(latestResults)resetPlayback();});document.querySelector('#autoPlay').addEventListener('click',()=>{if(!latestResults)return;if(playback.timer)return stopAutoPlay();playback.timer=setInterval(()=>movePlayback(1),750);document.querySelector('#autoPlay').textContent='■ Stop';});document.querySelectorAll('[data-playback]').forEach(tab=>tab.addEventListener('click',()=>{playback.mode=tab.dataset.playback;playback.step=0;stopAutoPlay();renderPlayback();}));
document.querySelector('#runSimulation').addEventListener('click',()=>{const error=validate();document.querySelector('#errorMessage').textContent=error||'';if(error)return;const config={fixed:Number(document.querySelector('#fixedQuantum').value),min:Number(document.querySelector('#minQuantum').value),max:Number(document.querySelector('#maxQuantum').value),switchCost:Number(document.querySelector('#switchCost').value)};const rr=simulate(processes,'fixed',config),arr=simulate(processes,'adaptive',config);latestResults={rr,arr,config};renderResults(rr,arr,config);document.querySelector('#results').scrollIntoView({behavior:'smooth',block:'start'});});
document.querySelector('#exportCsv').addEventListener('click',()=>{if(!latestResults)return;const data=[['Algorithm','PID','Completion Time','Turnaround Time','Waiting Time','Response Time','Context Switches','CPU Utilization','Throughput']];for(const [name,result] of [['Round Robin',latestResults.rr],['Adaptive Round Robin',latestResults.arr]])result.metrics.forEach(m=>data.push([name,m.id,m.completion,m.turnaround,m.waiting,m.response,result.contextSwitches,result.utilization.toFixed(2),result.throughput.toFixed(3)]));const blob=new Blob([data.map(row=>row.join(',')).join('\n')],{type:'text/csv'}),link=Object.assign(document.createElement('a'),{href:URL.createObjectURL(blob),download:'arr-scheduling-results.csv'});link.click();URL.revokeObjectURL(link.href);});
renderRows();

const baseRenderResults = renderResults;
renderResults = function enhancedRenderResults(rr, arr, config) {
  baseRenderResults(rr, arr, config);
  const switchDifference = rr.contextSwitches - arr.contextSwitches;
  const waitDifference = rr.averages.waiting - arr.averages.waiting;
  const responseDifference = rr.averages.response - arr.averages.response;
  const conclusionTitle = switchDifference > 0 ? 'Adaptive RR is more efficient for this workload.' : switchDifference < 0 ? 'Fixed RR is more efficient for this workload.' : 'The policies have equal switching overhead here.';
  const conclusionText = `In this simulation, Adaptive RR uses ${arr.contextSwitches} context switches against ${rr.contextSwitches} for fixed RR and produces an average waiting time of ${arr.averages.waiting.toFixed(2)}. The result is measured from the selected processes and settings, not assumed in advance.`;
  document.querySelector('#conclusionTitle').textContent = conclusionTitle;
  document.querySelector('#conclusionText').textContent = conclusionText;
  document.querySelector('#impactPoints').innerHTML = `<div class="impact-point"><b>What it proves</b>${switchDifference === 0 ? 'Quantum adaptation did not change switching for this input.' : `The selected policy changes overhead by ${Math.abs(switchDifference)} process switches.`}</div><div class="impact-point"><b>Workload impact</b>${waitDifference >= 0 ? `ARR lowers average waiting by ${waitDifference.toFixed(2)} units.` : `ARR raises average waiting by ${Math.abs(waitDifference).toFixed(2)} units.`}</div><div class="impact-point"><b>Trade-off to discuss</b>${responseDifference >= 0 ? `ARR improves average response by ${responseDifference.toFixed(2)} units.` : `ARR has ${Math.abs(responseDifference).toFixed(2)} more response-time units.`}</div>`;
  const busyTime = processes.reduce((total, process) => total + process.burst, 0);
  const idleTime = Math.max(0, arr.totalTime - busyTime - arr.overheadTime);
  const utilization = Math.min(100, arr.utilization);
  document.querySelector('#efficiencyDonut').style.background = `conic-gradient(var(--teal) ${utilization * 3.6}deg, var(--amber) ${utilization * 3.6}deg ${(utilization + (arr.overheadTime / arr.totalTime * 100)) * 3.6}deg, #e5ebef ${(utilization + (arr.overheadTime / arr.totalTime * 100)) * 3.6}deg)`;
  document.querySelector('#utilizationValue').textContent = `${utilization.toFixed(1)}%`;
  document.querySelector('#efficiencyLegend').innerHTML = `<div><span>Useful CPU work</span><b>${busyTime} units</b></div><div><span>Switch overhead</span><b>${arr.overheadTime} units</b></div><div><span>Idle CPU time</span><b>${idleTime} units</b></div><div><span>Total finish time</span><b>${arr.totalTime} units</b></div>`;
};

const osInsights = [
  { question:'Why does Round Robin use a time quantum?', answer:'A time quantum prevents one CPU-bound process from keeping the processor for too long. Every ready process gets a turn, improving fairness and interactive responsiveness.', quote:'Fair scheduling is not giving everyone the same outcome; it is giving everyone a meaningful chance to run.' },
  { question:'What is a context switch?', answer:'It is the CPU changing from one process to another by saving the current state and restoring another state. It enables multitasking, but it also uses time without completing application work.', quote:'A fast switch is useful. An unnecessary switch is overhead.' },
  { question:'Why use a median for Adaptive Round Robin?', answer:'The median is less affected by one unusually long burst than an average. It provides a stable, explainable quantum that reflects the middle of the ready queue.', quote:'A good scheduling rule listens to the workload before deciding how long to run.' },
  { question:'What is the difference between waiting and response time?', answer:'Waiting time is all time spent in the ready queue. Response time is only the delay before a process first receives the CPU. Interactive users notice response time first.', quote:'The first response creates the user experience; total waiting defines the cost.' },
  { question:'Can Adaptive Round Robin always beat fixed Round Robin?', answer:'No. ARR is a workload-dependent heuristic. The simulator compares measured results because different arrivals, burst patterns, and quantum bounds can favour different policies.', quote:'In operating systems, a measured trade-off is more valuable than an untested promise.' }
];
let activeInsight = 0;
const insightSlide = document.querySelector('#insightSlide');
const insightDots = document.querySelector('#insightDots');
function renderInsight() {
  const insight = osInsights[activeInsight];
  insightSlide.innerHTML = `<div><p class="insight-question"><span>Q${activeInsight + 1}.</span> ${insight.question}</p><p class="insight-answer">${insight.answer}</p></div><blockquote class="insight-quote">${insight.quote}</blockquote>`;
  insightDots.innerHTML = osInsights.map((_, index) => `<button class="insight-dot ${index === activeInsight ? 'active' : ''}" data-insight="${index}" aria-label="Show insight ${index + 1}"></button>`).join('');
}
function changeInsight(direction) { activeInsight = (activeInsight + direction + osInsights.length) % osInsights.length; renderInsight(); }
document.querySelector('#previousInsight').addEventListener('click', () => changeInsight(-1));
document.querySelector('#nextInsight').addEventListener('click', () => changeInsight(1));
insightDots.addEventListener('click', event => { const dot = event.target.closest('[data-insight]'); if (!dot) return; activeInsight = Number(dot.dataset.insight); renderInsight(); });
renderInsight();
setInterval(() => changeInsight(1), 7000);
